version: '3'

services:
  amoure-be-db:
    image: postgres:13.4
    restart: always
    hostname: amoure-db
    networks:
      local:
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 3s
      retries: 5
    env_file: .env
    ports:
      - '5432:5432'

networks:
  local:
    driver: bridge